[features]
resolution = true
skip-lint = false

[programs.devnet]
anchor-counter-session = "4aKBdeF93xKdfRizpCxFJFPT68p7tXdJjkPUDhon539c"

[programs.localnet]
anchor-counter-session = "4aKBdeF93xKdfRizpCxFJFPT68p7tXdJjkPUDhon539c"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "../fullstack-test.sh"